# Generated by Django 5.0.3 on 2024-06-19 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabilidadFuerza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Lightsaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=128)),
                ('año_creación', models.DateField()),
                ('color', models.CharField(choices=[('Azul', 'Azul'), ('Verde', 'Verde'), ('Rojo', 'Rojo'), ('Violeta', 'Violeta'), ('Amarillo', 'Amarillo')], default='Azul', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioFuerza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('sith', models.BooleanField(default=False)),
                ('HabilidadesDisponibles', models.ManyToManyField(blank=True, to='jedi_api.habilidadfuerza')),
                ('Sable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jedi_api.lightsaber')),
            ],
        ),
    ]
