# Generated by Django 5.0.3 on 2024-06-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedi_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidadfuerza',
            name='dificultad',
            field=models.CharField(choices=[], default='Fácil', max_length=20),
        ),
    ]
